### ISSUE TITLE
Can´t put your qtdragon with tools image working

### ISSUE THREAD

**Issue by MarcoGasparcnc** [persei802/QtDragon_hd#4]
Congrats for your Qtdragon :D

I'm using you qtdragon_hd

Issues:
   -F2 key only do machine off and don't do machine ON.
   -To execute mdi command have to press Enter Key  (axis let start with doubble click in the mdi command.

Can't upgrade to qtdragon with tools images.... don't know where to put the files.

**Comment by persei802** [comment]
Hello Marco. 

I modified the F2 key to toggle machine state ON/OFF.

When in MDI mode, commands can be entered by pressing the keyboard ENTER key or the ENTER button on the GUI GCODE panel. Mouse double clicks are not supported.

Tool images go into a folder called tool_icons in the CONFIG directory. For example, mine are in /home/jim/linuxcnc/configs/qtdragon_hd/tool_icons. Images should be 160 x 270 and be png format, which allows transparent backgrounds.

Thanks for the feedback.
Jim

**Comment by MarcoGasparcnc** [comment]
Hello,

Thanks for the change :D

Can't Power on

-- 
Atentamente,
Marco Gaspar

A 2024-02-22 15:09, Jim escreveu:

> Hello Marco.
> 
> I modified the F2 key to toggle machine state ON/OFF.
> 
> When in MDI mode, commands can be entered by pressing the keyboard 
> ENTER key or the ENTER button on the GUI GCODE panel. Mouse double 
> clicks are not supported.
> 
> Tool images go into a folder called tool_icons in the CONFIG directory. 
> For example, mine are in 
> /home/jim/linuxcnc/configs/qtdragon_hd/tool_icons. Images should be 160 
> x 270 and be png format, which allows transparent backgrounds.
> 
> Thanks for the feedback.
> Jim
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/persei802/QtDragon_hd/issues/4#issuecomment-1959650769
[2]

**Comment by MarcoGasparcnc** [comment]
Hello,

Thanks for the change :D

Can't Power on with XYZA config

![2024-02-22 16_18_45-1 376 914 537 - AnyDesk](https://github.com/persei802/QtDragon_hd/assets/24980048/774c6667-4772-4a3d-9553-1a0123f2e7e9)

Hitting F2 Error
![2024-02-22 16_21_28-1 376 914 537 - AnyDesk](https://github.com/persei802/QtDragon_hd/assets/24980048/e5b713b5-09be-4893-93ec-a6f3c26ad6cf)


Changing to XYZ Config the layout is diferent and no tool images.

![2024-02-22 17_02_38-1 376 914 537 - AnyDesk](https://github.com/persei802/QtDragon_hd/assets/24980048/066cf9ac-b9aa-4075-a0a7-aa0f5876658e)


Best Regards,
Marco Gaspar

**Comment by MarcoGasparcnc** [comment]
Copying to a working mesa card config i get:

Traceback (most recent call last):
  File "/usr/bin/qtvcp", line 555, in <module>
    _qtvcp = QTVCP()
             ^^^^^^^
  File "/usr/bin/qtvcp", line 294, in __init__
    window.handler_instance.initialized__()
  File "/home/mjg/linuxcnc/configs/cnc/qtdragon/qtdragon_handler.py", line 174, in initialized__
    self.w[item].hide()
    ~~~~~~^^^^^^
  File "/usr/lib/python3/dist-packages/qtvcp/qt_makegui.py", line 498, in __getitem__
    return getattr(self, item)
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'VCPWindow' object has no attribute 'lbl_rotary_setting'

**Comment by persei802** [comment]
XYZA config - it looks like you're using these files in simulation mode. The XYZA config uses gantrysim.hal which already connects the ESTOP loop. To fix this, add the following lines to qtdragon_postgui.hal:
unlinkp iocontrol.-.user-enable-out
unlinkp iocontrol.0.emc-enable-in
Actually, I pushed the fixed file.

Fixed: lbl_rotary_setting issue.

Your XYZ screen is not part of this distro. That is the old version from the linuxcnc samples. Maybe you somehow got some files mixed up?

One other thing to mention is that in order for tool icons to work, you need to have sqlite installed. 
You're also missing some images, like jog buttons and machine power. These are available in the qtdragon/images folder.
Jim

**Comment by MarcoGasparcnc** [comment]
Hello,

This is a fresh install of the https://www.linuxcnc.org/iso/LinuxCNC_2.9.2-amd64.hybrid.iso  

I create a new pncconf dir and copy your files to there.

![With_My_Config](https://github.com/persei802/QtDragon_hd/assets/24980048/49d24ff2-a527-4730-aaac-81a2393a6155)

images folder
![Images](https://github.com/persei802/QtDragon_hd/assets/24980048/d11af010-0ca4-4a21-9bef-e6ea33075402)

**Comment by MarcoGasparcnc** [comment]
My Estop is active and don't show active :
"net estop-ext     <=  [HMOT](CARD0).7i76.0.0.input-09-not"

![estop1](https://github.com/persei802/QtDragon_hd/assets/24980048/75331e54-3def-4b2c-85e1-61273d05781e)
![estop2](https://github.com/persei802/QtDragon_hd/assets/24980048/a3a9013d-8426-434e-9d6b-eed06b9a4d3e)

**Comment by MarcoGasparcnc** [comment]
Changing the style Sheet

![estopimages](https://github.com/persei802/QtDragon_hd/assets/24980048/de21b136-d36f-42cc-a0e8-8a6757012ed1)
![Uploading estopimages2.png…]()

**Comment by MarcoGasparcnc** [comment]
Changing the style Sheet

![estopimages2](https://github.com/persei802/QtDragon_hd/assets/24980048/90420bd1-69a1-4236-856a-1ed8b1f76efc)
![estopimages](https://github.com/persei802/QtDragon_hd/assets/24980048/f656f476-6838-4937-b97d-70734c363b76)

**Comment by persei802** [comment]
I guess I should have asked you first what version of linuxcnc you were using. It doesn't work with 2.9, You need 2.10 (master).
Also, it only works with the stylesheets supplied in this repo. qtdragon.qss is from the sample sim configs in /usr/share/qtvcp. The stylesheet editor dialog is a qtvcp widget and I have no control over what it shows. However, I will look into it, maybe there's a fix.
I think the ESTOP issue is also related to using version 2.9. Sorry for the confusion.
Jim

**Comment by MarcoGasparcnc** [comment]
Hello,

I'm using the last 2.10 version.

If it helps i can give you my anydesk id so you can check what can be the problem.

**Comment by persei802** [comment]
I prefer not using anydesk. I would not want to be responsible for destroying your computer. Please send your ini and hal files directly to my email and I will have a look.

**Comment by MarcoGasparcnc** [comment]
What is your email?

marco@marcogaspar.net

**Comment by persei802** [comment]
I checked your files and found the following:

You have a whole bunch of MDI_COMMANDs. The ones under [HALUI] should probably be moved. The current handler only manages up to 10 macros, but I pushed an update to handle up to 20 and any excess are ignored. Also, the new format is MDI_COMMAND_MACROn = ...
They should be numbered sequentially without skipping any numbers. 

If the display in full HD is cutting off the bottom statusbar, in the line DISPLAY = qtvcp -m qtdragon , change -m to -f.

I pushed an update to assign button icons programatically rather than relying on qtdesigner.

The tool icons are working properly, you just haven't defined them.
In the TOOL page, click TOOL DATABASE -> ENABLE EDIT and click on a tool number. On the right side, click on the ICON column and from the dropdown box, select an icon to assign to that tool. Uncheck ENABLE EDIT to finish. Now when you load a tool, it's icon is displayed on the TOOL frame.

Your ESTOP net only connects an external input to the emc-enable-in. The GUI button hal pin is not connected and therefore has no effect on ESTOP state. As an example, I have 2 external ESTOP signals and the GUI ESTOP button connected to emc-enable-in.
## ESTOP
net ext_estop       and2.0.in0 <= hm2_7i96.0.gpio.000.in
net mpg-estop       and2.0.in1 <= hm2_7i96.0.gpio.047.in_not
net ext_and         and2.1.in0 <= and2.0.out
net ui_estop        and2.1.in1 <= qtdragon.btn_estop
net estop           and2.1.out => iocontrol.0.emc-enable-in
Obviously, if you only have 1 external signal, you don't need the 2 AND2 components.

Hopefully, this gets you running.
Jim

**Comment by MarcoGasparcnc** [comment]
Hello,

Doing Cycle Start the machine do nothing.....   if i click Cycle start Again is shows Program already running...
![Screenshot_2024-02-25_21-12-10](https://github.com/persei802/QtDragon_hd/assets/24980048/ad7db930-716c-437d-9480-a8f820567695)

**Comment by MarcoGasparcnc** [comment]
With Axis it runs...

![Screenshot_2024-02-25_22-31-59](https://github.com/persei802/QtDragon_hd/assets/24980048/320ed236-4027-4df7-8d02-55e93550d9ba)

**Comment by persei802** [comment]
You need to check your HAL connections again. The screen shows ESTOP active but machine ON. This should not be possible.
What is the ESTOP LED connected to in HAL?  What is the reason to combine your machine specific HAL file and postgui HAL stuff into a single file? They really should be separated. If you go into HAL SHOW, you can inspect the state of every hal pin.
Jim
