### ISSUE TITLE
Probe Error

### ISSUE THREAD

**Issue by MarcoGasparcnc** [persei802/QtDragon_hd#5]
Hello,

Using any probe cycling... in this case inner center it start the cycle, after touching the first point the machine stops and get error "name is not defined".

![1719003697143](https://github.com/persei802/QtDragon_hd/assets/24980048/13a4e2ac-a79f-4d7e-a06a-4a4230e231c0)
![1719003697155](https://github.com/persei802/QtDragon_hd/assets/24980048/d6d31d5e-24f8-4da4-a920-8f4244b826af)
![1719003697163](https://github.com/persei802/QtDragon_hd/assets/24980048/0fdb2347-db99-4dad-be22-20e1e3c931ee)

Best Regards,
Marco Gaspar

**Comment by persei802** [comment]
I haven't done any work on this for several months and now my development computer is toast. It will take me a little time to restore everything before I can look into this issue. 
Jim

**Comment by persei802** [comment]
I am not able to reproduce this error. Can you start Linuxcnc from a terminal and capture any python error messages as well as the terminal output? Have you modified any of the .ui files?
Jim
